apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: "grafana/grafana:latest"
          imagePullPolicy: Always
          env:
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "true"
            - name: GF_USERS_AUTO_ASSIGN_ORG
              value: "true"
            - name: GF_UNIFIED_ALERTING_ENABLED
              value: "true"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-volume
              mountPath: /var/lib/grafana
      initContainers:
        - name: mod-dir-owner
          image: alpine:3
          command: ["/bin/sh", "-c", "chown 1000:1000 /var/lib/grafana"]
          volumeMounts:
            - name: grafana-volume
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-volume
          hostPath:
            path: /mnt/raid/grafana
            type: DirectoryOrCreate