apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: logs
spec:
  selector:
    app: loki
  ports:
  - name: http-metrics
    port: 3100
    targetPort: 3100
    nodePort: 30004
  - name: grpc
    port: 9095
    targetPort: 9095
    nodePort: 30005
  type: NodePort