apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrising
  namespace: game-servers
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: vrising
  template:
    metadata:
      labels:
        app: vrising
    spec:
      containers:
        - name: vrising
          image: "mpstefan/vrising:latest"
          imagePullPolicy: Always
          env:
            - name: VR_NAME
              value: "[US East][60fps] Ebon Garden | Casual PvP | 6/27 Launch"
            - name: VR_DESCRIPTION
              value: "Ebon Garden will never be wiped and is actively monitored for performance issues. Join our Discord here: https://discord.gg/nkKd9sDX8s"
            - name: VR_GAME_PORT
              value: "9876"
            - name: VR_QUERY_PORT
              value: "9877"
            - name: VR_MAX_USERS
              value: "40"
            - name: VR_MAX_ADMINS
              value: "4"
            - name: VR_FPS
              value: "60"
            - name: VR_SECURE
              value: "true"
            - name: VR_LIST_ON_MASTER_SERVER
              value: "true"
            - name: VR_SAVE_NAME
              value: "EbonGarden"
            - name: VR_SAVE_COUNT
              value: "20"
            - name: VR_SAVE_INTERVAL
              value: "120"
          ports:
            - name: game
              containerPort: 9876
              protocol: UDP
            - name: query
              containerPort: 9877
              protocol: UDP
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "6Gi"
              cpu: "4"
          volumeMounts:
            - name: home-volume
              mountPath: /home/ips-hosting
            - name: game-settings
              mountPath: /home/ips-hosting/VRisingServer_Data/StreamingAssets/Settings/ServerGameSettings.json
              subPath: ServerGameSettings.json
      initContainers:
        - name: mod-home-owner
          image: alpine:3
          command: ["/bin/sh", "-c", "chown 1000:1000 /home/ips-hosting"]
          volumeMounts:
            - name: home-volume
              mountPath: /home/ips-hosting
            - name: game-settings
              mountPath: /home/ips-hosting/VRisingServer_Data/StreamingAssets/Settings/ServerGameSettings.json
              subPath: ServerGameSettings.json
      volumes:
        - name: home-volume
          hostPath:
            path: /mnt/raid/vrising
            type: DirectoryOrCreate
        - name: game-settings
          configMap:
            name: vrising-game-settings
          
          