apiVersion: apps/v1
kind: Deployment
metadata:
  name: vrising
  namespace: game-servers
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: vrising
  template:
    metadata:
      labels:
        app: vrising
    spec:
      securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
      containers:
        - name: vrising
          image: "mpstefan/vrising:latest"
          imagePullPolicy: Always
          env:
            - name: VR_NAME
              value: "Ebon Garden"
            - name: VR_DESCRIPTION
              value: "Ebon Garden is a PvE server open to all levels of play."
            - name: VR_GAME_PORT
              value: "9876"
            - name: VR_QUERY_PORT
              value: "9877"
            - name: VR_MAX_USERS
              value: "40"
            - name: VR_MAX_ADMINS
              value: "4"
            - name: VR_FPS
              value: "60"
            - name: VR_SECURE
              value: "true"
            - name: VR_LIST_ON_MASTER_SERVER
              value: "false"
            - name: VR_SAVE_NAME
              value: "EbonGarden"
            - name: VR_SAVE_COUNT
              value: "20"
            - name: VR_SAVE_INTERVAL
              value: "120"
          ports:
            - name: game
              containerPort: 9876
              protocol: UDP
            - name: query
              containerPort: 9877
              protocol: UDP
          resources:
            limits:
              memory: "4Gi"
              cpu: "4"
          volumeMounts:
          - name: homeVolume
            mountPath: /home/ips-hosting
      volumes:
        - name: homeVolume
          hostPath:
            path: /mnt/raid
            type: Directory