apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: vrising
  ports:
  - name: vrising-game
    protocol: UDP
    port: 9876
    targetPort: game
  - name: vrising-query
    protocol: UDP
    port: 9877
    targetPort: query
