apiVersion: v1
kind: Service
metadata:
  name: valheim
  namespace: game-servers
spec:
  selector:
    app: valheim
  ports:
  - name: valheim-game1
    protocol: UDP
    nodePort: 30008
    port: 2456
    targetPort: game1
  - name: valheim-game1tcp
    protocol: TCP
    nodePort: 30008
    port: 2456
    targetPort: game1tcp
  - name: valheim-game2
    protocol: UDP
    nodePort: 30009
    port: 2457
    targetPort: game2
  - name: valheim-game2tcp
    protocol: TCP
    nodePort: 30009
    port: 2457
    targetPort: game2tcp
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: valheim-metrics
  namespace: game-servers
spec:
  selector:
    app: valheim
  ports:
  - name: valheim-metrics
    port: 9100
    targetPort: 9100