apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: game-servers
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: "mpstefan/minecraft:latest"
          imagePullPolicy: Always
          ports:
            - name: game
              containerPort: 25565
              protocol: TCP
            - name: dynmap
              containerPort: 8123
              protocol: TCP
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "13Gi"
              cpu: "4"
          volumeMounts:
            - name: plugins-volume
              mountPath: /home/minecraft/plugins
            - name: world
              mountPath: /home/minecraft/Telvanni
            - name: world-nether
              mountPath: /home/minecraft/Telvanni_nether
            - name: world-the-end
              mountPath: /home/minecraft/Telvanni_the_end
            - name: server-properties
              mountPath: /home/minecraft/server.properties
              subPath: server.properties
            - name: spigot-settings
              mountPath: /home/minecraft/spigot.yml
              subPath: spigot.yml
            - name: paper-global
              mountPath: /home/minecraft/config/paper-global.yml
              subPath: paper-global.yml
            - name: paper-world-defaults
              mountPath: /home/minecraft/config/paper-world-defaults.yml
              subPath: paper-world-defaults.yml
            - name: whitelist
              mountPath: /home/minecraft/whitelist.json
            - name: ops
              mountPath: /home/minecraft/ops.json
            - name: banned-ips
              mountPath: /home/minecraft/banned-ips.json
            - name: banned-players
              mountPath: /home/minecraft/banned-players.json
      initContainers:
        - name: mod-home-owner
          image: alpine:3
          command: ["/bin/sh"]
          args:
            - -c
            - >-
                chown 1001:1000 /home/minecraft &&
                chown -R 1001:1000 /home/minecraft/plugins &&
                chown 1001:1000 /home/minecraft/config &&
                chown -R 1001:1000 /home/minecraft/Telvanni &&
                chown -R 1001:1000 /home/minecraft/Telvanni_nether &&
                chown -R 1001:1000 /home/minecraft/Telvanni_the_end
          volumeMounts:
            - name: plugins-volume
              mountPath: /home/minecraft/plugins
            - name: world
              mountPath: /home/minecraft/Telvanni
            - name: world-nether
              mountPath: /home/minecraft/Telvanni_nether
            - name: world-the-end
              mountPath: /home/minecraft/Telvanni_the_end
            - name: server-properties
              mountPath: /home/minecraft/server.properties
              subPath: server.properties
            - name: spigot-settings
              mountPath: /home/minecraft/spigot.yml
              subPath: spigot.yml
            - name: paper-global
              mountPath: /home/minecraft/config/paper-global.yml
              subPath: paper-global.yml
            - name: paper-world-defaults
              mountPath: /home/minecraft/config/paper-world-defaults.yml
              subPath: paper-world-defaults.yml
            - name: whitelist
              mountPath: /home/minecraft/whitelist.json
            - name: ops
              mountPath: /home/minecraft/ops.json
            - name: banned-ips
              mountPath: /home/minecraft/banned-ips.json
            - name: banned-players
              mountPath: /home/minecraft/banned-players.json
            
      volumes:
        - name: plugins-volume
          hostPath:
            path: /mnt/raid/minecraft/plugins
            type: DirectoryOrCreate
        - name: world
          hostPath:
            path: /mnt/raid/minecraft/Telvanni
            type: Directory
        - name: world-nether
          hostPath:
            path: /mnt/raid/minecraft/Telvanni_nether
            type: Directory
        - name: world-the-end
          hostPath:
            path: /mnt/raid/minecraft/Telvanni_the_end
            type: Directory
        - name: server-properties
          configMap:
            name: minecraft-server-properties
        - name: spigot-settings
          configMap:
            name: minecraft-spigot-settings
        - name: paper-global
          configMap:
            name: minecraft-paper-global
        - name: paper-world-defaults
          configMap:
            name: minecraft-paper-world-defaults
        - name: whitelist
          hostPath:
            path: /mnt/raid/minecraft/whitelist.json
            type: FileOrCreate
        - name: ops
          hostPath:
            path: /mnt/raid/minecraft/ops.json
            type: FileOrCreate
        - name: banned-ips
          hostPath:
            path: /mnt/raid/minecraft/banned-ips.json
            type: FileOrCreate
        - name: banned-players
          hostPath:
            path: /mnt/raid/minecraft/banned-players.json
            type: FileOrCreate