apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: game-servers
spec:
  selector:
    app: minecraft
  ports:
  - name: minecraft-game
    protocol: TCP
    nodePort: 30006
    port: 25565
    targetPort: game
  - name: minecraft-dynmap
    protocol: TCP
    nodePort: 30007
    port: 8123
    targetPort: dynmap

  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-metrics
  namespace: game-servers
spec:
  selector:
    app: minecraft
  ports:
  - name: minecraft-metrics
    port: 9100
    targetPort: 9100