apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: metrics
spec:
  selector:
    app: kube-state-metrics
  ports:
  - name: port
    port: 8080
    targetPort: port
  - name: telemetry
    port: 8081
    targetPort: telemetry