apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus
  namespace: metrics
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'prometheus'
        scheme: http
        metrics_path: '/metrics'
        static_configs:
          - targets: ['localhost:9090']
            labels:
              pod: prometheus

      - job_name: 'node-metrics'
        metrics_path: '/metrics'
        scheme: http
        static_configs:
          - targets: ['localhost:9100']

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
          api_server: https://kubernetes.default.svc:443
          tls_config:
            ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          bearer_token_file: "/var/run/secrets/kubernetes.io/serviceaccount/token"

      - job_name: 'grafana'
        metrics_path: '/metrics'
        scheme: http
        static_configs:
          - targets: ['grafana.grafana.svc.cluster.local:3000']
            labels:
              pod: grafana
