apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus
  namespace: metrics
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'prometheus'
        scheme: http
        metrics_path: '/metrics'
        static_configs:
          - targets: ['localhost:9090']
            labels:
              pod: prometheus
      - job_name: 'vrising-metrics'
        metrics_path: '/metrics'
        honor_labels: true
        static_configs:
          - targets: ['vrising-metrics.game-servers.svc.cluster.local:9100']
            labels:
              pod: vrising
      - job_name: 'grafana'
        metrics_path: '/metrics'
        honor_labels: true
        static_configs:
          - targets: ['grafana.grafana.svc.cluster.local:3000']
            labels:
              pod: grafana