apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: "prom/prometheus:v2.36.2"
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
        - name: node-exporter
          image: "prom/node-exporter:v1.3.1"
          ports:
            - containerPort: 9100
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus